# Job-Template: Auto Reboot Kick
# Env Parameter: eda_server-url 
# Survey Parameter: ticket_no, action_memo
- name: Auto Reboot Kick
  hosts: demo_server
  tasks:
    - name: Call EDA Rulebook
      ansible.builtin.uri:
        url: "{{ eda_server-url }}"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
        body: |-
          {
            "request": "auto_reboot",
            "ticket_no": "{{ ticket_no }}",
            "action_memo": "{{ action_memo }}"
          }
      register: result_powera

    - name: powerautomete debug
      ansible.builtin.debug:
        var: result_powera