- name: redmine post issue
  hosts: demo_server
  tasks:
    - name: Post Issue
      ansible.builtin.uri:
        url: http://{{ ip_address }}:3000/issues.json
        method: POST
        body_format: json
        status_code: 201
        return_content: true
        headers:
          Content-Type: application/json
          X-Redmine-API-Key: "{{ api_key }}"
        body: |-
          {
            "issue": {
              "project_id": "{{ issue.project_id }}",
              "tracker_id": "{{ issue.tracker_id }}",
              "subject": "{{ issue.subject }}",
              "description": "{{ issue.description }}",
              "custom_fields":[
                {"id":1,"value":"{{ issue.system_name }}"},
                {"id":2,"value":"{{ issue.timestamp }}"},
                {"id":3,"value":"{{ issue.err_id }}"},
                {"id":4,"value":"{{ issue.err_target }}"},
                {"id":5,"value":"{{ issue.err_code }}"},
                {"id":6,"value":"{{ issue.context }}"}
              ]
            }
          }
      register: result

    - name: debug
      ansible.builtin.debug:
        var: result