- name: redmine put issue
  hosts: demo_server
  tasks:
    - name: Get Issue
      ansible.builtin.uri:
        url: http://{{ ip_address }}:3000/issues/{{ ticket_no }}.json
        method: GET
        return_content: true
        headers:
          Content-Type: application/json
          X-Redmine-API-Key: "{{ api_key }}" 
      register: result_get

    - name: Update Issue
      vars:
        datetime: '{{ lookup(''pipe'', ''date "+%Y-%m-%d %H:%M:%S"'') }}'

      ansible.builtin.uri:
        url: http://{{ ip_address }}:3000/issues/{{ ticket_no }}.json
        method: PUT
        body_format: json
        status_code: 204
        return_content: true
        headers:
          Content-Type: application/json
          X-Redmine-API-Key: "{{ api_key }}"
        body: |-
          {
            "issue": {
              "status_id": "{{ status_id }}",
              "custom_fields":[
                {"id":6,"value":"{{ result_get.custom_fields[5].value }}\\n{{ context }}:{{ datetime }}"}
              ]
            }
          }
      register: result_put

    - name: debug
      ansible.builtin.debug:
        var: result_put
