- name: redmine put issue
  hosts: demo_server
  tasks:
    - name: Update Issue
      ansible.builtin.uri:
        url: http://{{ ip_address }}:3000/issues/{{ ticket_no }}.json
        method: PUT
        body_format: json
        status_code: 204
        return_content: true
        headers:
          Content-Type: application/json
          X-Redmine-API-Key: "{{ api_key }}"
        body: |-
          {
            "issue": {
              "status_id": "{{ status_id }}"
            }
          }
      register: result

    - name: debug
      ansible.builtin.debug:
        var: result
