# Job-Template: Redmine Issue Update Close
# Env Parameter: ip_address, api_key 
# Survey Parameter: ticket_no, status_id, context 
- name: redmine put issue
  hosts: demo_server
  tasks:
    - name: Get Issue
      ansible.builtin.uri:
        url: http://{{ ip_address }}:3000/issues/{{ ticket_no }}.json
        method: GET
        return_content: true
        headers:
          Content-Type: application/json
          X-Redmine-API-Key: "{{ api_key }}" 
      register: result_get

    - name: Update Issue
      vars:
        date1: '{{ lookup(''pipe'', ''date "+%Y-%m-%d %H:%M:%S"'') }}'
        date2: "{{ date1 | to_datetime('%Y-%m-%d %H:%M:%S') }}"
        date3: '{{ lookup(''pipe'', ''date -d "{{ date2 }} 9 hour" "+%Y-%m-%d %H:%M:%S"'') }}'
        date4: "{{ date3 | to_datetime('%Y-%m-%d %H:%M:%S') }}"

        date_start_second: "{{ (result_get.json.issue.custom_fields[1].value | to_datetime('%Y-%m-%d %H:%M:%S')).timestamp() }}"
        date_close_second: "{{ (date4 | to_datetime('%Y-%m-%d %H:%M:%S')).timestamp() }}"
        action_time_tsec: "{{ ((date_close_second | int) - (date_start_second | int) | int) }}"

        action_time_hour: "{{ action_time_tsec / 3600 | int }}"
        action_time_tsec2: "{{ action_time_tsec - action_time_hour * 3600 | int}}"
        action_time_min: "{{ action_time_tsec2 / 60 | int }}"
        action_time_sec: "{{ action_time_tsec2 - action_time_min * 60 | int}}" 
        # action_time_min: "{{ ((date_close_second | int) - (date_start_second | int)) / (60) }}"

      ansible.builtin.uri:
        url: http://{{ ip_address }}:3000/issues/{{ ticket_no }}.json
        method: PUT
        body_format: json
        status_code: 204
        return_content: true
        headers:
          Content-Type: application/json
          X-Redmine-API-Key: "{{ api_key }}"
        body: |-
          {
            "issue": {
              "status_id": "{{ status_id }}",
              "custom_fields":[
                {"id":6,"value":"{{ result_get.json.issue.custom_fields[5].value }},{{ context }}:{{ date3 }},---,total-time:{{ action_time_hour }}h{{ action_time_min }}m{{ action_time_sec }}s"}
              ]
            }
          }
      register: result_put

    - name: debug
      ansible.builtin.debug:
        var: result_put
