# Job-Template: Teams Close Notification
# Env Parameter:ip_address, api_key, powerautomate_webhook_url, ex_ip_address 
# Survey Parameter:ticket_no 
- name: Teams Close Notification
  hosts: demo_server
  tasks:
    - name: Get Issue
      ansible.builtin.uri:
        url: http://{{ ip_address }}:3000/issues/{{ ticket_no }}.json
        method: GET
        return_content: true
        headers:
          Content-Type: application/json
          X-Redmine-API-Key: "{{ api_key }}" 
      register: result_get

    - name: Powerautomates call close-notify
      ansible.builtin.uri:
        url: "{{ powerautomate_webhook_url }}"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
        body: |-
          {
            "subject": "{{ result_get.json.issue.subject }}",
            "system_name": "{{ result_get.json.issue.custom_fields[0].value }}",
            "err_id": "{{ result_get.json.issue.custom_fields[2].value }}",
            "timestamp": "{{ result_get.json.issue.custom_fields[1].value }}",
            "err_target": "{{ result_get.json.issue.custom_fields[3].value }}",
            "err_code": "{{ result_get.json.issue.custom_fields[4].value }}",
            "description": "{{ result_get.json.issue.description }}",
            "ticket_no": "{{ ticket_no }}",
            "redmine": "http://{{ ex_ip_address }}:3000/issues/{{ ticket_no }}",
            "action": "- {{ result_get.json.issue.custom_fields[5].value | regex_replace(',', '\r- ') }}" 
          }
      register: result_powera