- name: Teams action notification
  hosts: demo_server
  tasks:
    - name: Redmine Post Issue
      vars:
        date1: '{{ lookup(''pipe'', ''date "+%Y-%m-%d %H:%M:%S"'') }}'
        date2: "{{ date1 | to_datetime('%Y-%m-%d %H:%M:%S') }}"
        date3: '{{ lookup(''pipe'', ''date -d "{{ date2 }} 9 hour" "+%Y/%m/%d %H:%M:%S"'') }}'

      ansible.builtin.uri:
        url: http://{{ ip_address }}:3000/issues.json
        method: POST
        body_format: json
        status_code: 201
        return_content: true
        headers:
          Content-Type: application/json
          X-Redmine-API-Key: "{{ api_key }}"
        body: |- 
          {
            "issue": {
              "project_id": "{{ project_id }}",
              "tracker_id": "{{ tracker_id }}",
              "subject": "{{ subject }}",
              "description": "{{ description }}",
              "custom_fields":[
                {"id":1,"value":"{{ system_name }}"},
                {"id":2,"value":"{{ timestamp[:19] }}"},
                {"id":3,"value":"{{ err_id }}"},
                {"id":4,"value":"{{ err_target }}"},
                {"id":5,"value":"{{ err_code }}"},
                {"id":6,"value":"Error:{{ timestamp[:19] }},EventCreate:{{ date3 }}"}
              ]
            }
          } 
      register: result_post

    - name: debug
      ansible.builtin.debug:
        var: result_post