---
- name: Trouble Recover Reboot Rulebook
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5002

  rules:
    - name: Reboot & Recover
      condition: event.payload.request == "reboot"
      actions:
        - run_job_template:
            name: Sample-apl Start
            organization: Default

        - run_job_template:
            name: Redmine Issue Update With Description
            organization: Default
            job_args: 
              extra_vars: 
                ticket_no: '"{{ event.payload.ticket_no }}"'
                status_id: "2"
                context: "Action"
                action_memo: '"{{ event.payload.action_memo }}"'

         - run_job_template:
            name: Teams Complete Notification
            organization: Default
            job_args: 
              extra_vars: 
                ticket_no: '"{{ event.payload.ticket_no }}"'