# Webhook Parameter: request, ticket_no 
- name: Action Auto Reboot Rulebook
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5004

  rules:
    - name: Auto Reboot
      condition: event.payload.request == "auto_reboot"
      actions:
        - run_job_template:
            name: Redmine Issue Update With Description
            organization: Default
            job_args: 
              extra_vars: 
                ticket_no: '"{{ event.payload.ticket_no }}"'
                status_id: "2"
                context: "Action"
                action_memo: "自動再起動で対応(auto-reboot)"

        - run_job_template:
            name: Sample-apl Start
            organization: Default

        - run_job_template:
            name: Redmine Issue Update
            organization: Default
            job_args: 
              extra_vars: 
                ticket_no: '"{{ event.payload.ticket_no }}"'
                status_id: "3"
                context: "Complete"

        - run_job_template:
            name: Redmine Issue Update
            organization: Default
            job_args: 
              extra_vars: 
                ticket_no: '"{{ event.payload.ticket_no }}"'
                status_id: "5"
                context: "Close"

        - run_job_template:
            name: Teams Close Notification
            organization: Default
            job_args: 
              extra_vars: 
                ticket_no: '"{{ event.payload.ticket_no }}"'