- name: Error Recieve Rulebook
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Error Recieve
      condition: event.payload.system_name is defined
      actions:
        - run_job_template:
            name: Sample-apl Stop
            organization: Default