# Webhook Parameter: request, ticket_no 
- name: Trouble Recover Close Rulebook
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5003

  rules:
    - name: Close Trouble
      condition: event.payload.request == "close"
      actions:
        - run_job_template:
            name: Redmine Issue Update
            organization: Default
            job_args: 
              extra_vars: 
                ticket_no: '"{{ event.payload.ticket_no }}"'
                status_id: "3"
                context: "対応完了"

        - run_job_template:
            name: Redmine Issue Update Close
            organization: Default
            job_args: 
              extra_vars: 
                ticket_no: '"{{ event.payload.ticket_no }}"'
                status_id: "5"
                context: "クローズ"

        - run_job_template:
            name: Teams Close Notification
            organization: Default
            job_args: 
              extra_vars: 
                ticket_no: '"{{ event.payload.ticket_no }}"'