---
- name: Error Recieve Rulebook
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Error Recieve
      condition: event.payload.system_name is defined and event.payload.timestamp is defined and event.payload.err_id is defined and event.payload.err_target is defined and event.payload.err_code is defined and event.payload.context is defined and event.payload.memo is defined 
      actions:
        - run_job_template:
            name: Sample-apl Stop
            organization: Default

        - run_job_template:
            name: Redmine Issue Post
            organization: Default
            job_args: 
              extra_vars: 
                subject: '"[障害]{{ event.payload.err_id }}"'
                description: '"{{ event.payload.context }}\n{{ event.payload.memo }}"'
                system_name: '"{{ event.payload.system_name }}"'
                timestamp: '"{{ event.payload.timestamp }}"'
                err_id: '"{{ event.payload.err_id }}"'
                err_target: '"{{ event.payload.err_target }}"'
                err_code: '"{{ event.payload.err_code }}"'
                context: ""