---
- name: Error Recieve Rulebook
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Error Recieve
      condition: event.payload.system_name is defined  
      action:
        run_job_template:
          name: test_playbook3
          organization: Default
          job_args: 
            extra_vars: 
              systemname: '"{{ event.payload.system_name }}"'
              timestamp: '"{{ event.payload.timestamp }}"'
              errid: '"{{ event.payload.err_id }}"'
              errtarget: '"{{ event.payload.err_target }}"'
              errcode: '"{{ event.payload.err_code }}"'
              context: '"{{ event.payload.context }}"'
              memo: '"{{ event.payload.memo }}"'