---
- name: Error Recieve Rulebook
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Error Recieve
      condition: event.payload.system_name is defined 
      action:
        run_job_template:
          name: test_playbook3
          organization: Default
          job_args:
            extra_vars:
              system_name: "{{ event.payload.system_name }}"
              timestamp: Test-timestamp
              err_id: Test-err-id
              err_target: Test-err_target
              err_code: Test-err_code
              context: Test-context
              memo: Test-memo 