# Webhook Parameter: err_id, context, system_name, timestamp, err_target, err_code 
- name: Error Recieve Rulebook
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Error Stop And Error Notification
      condition: event.payload.system_name is defined
      actions:
        - run_job_template:
            name: Sample-apl Stop
            organization: Default

        - run_job_template:
            name: Error Judge
            organization: Default
            job_args: 
              extra_vars: 
                subject: '"[障害]{{ event.payload.err_id }}"'
                description: '"{{ event.payload.context }}"'
                system_name: '"{{ event.payload.system_name }}"'
                timestamp: '"{{ event.payload.timestamp }}"'
                err_id: '"{{ event.payload.err_id }}"'
                err_target: '"{{ event.payload.err_target }}"'
                err_code: '"{{ event.payload.err_code }}"'