---
- name: Error Recieve Rulebook
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Error Recieve
      condition: event.payload.system_name is defined 
      action:
        run_job_template:
          name: test_playbook3
          organization: Default
          job_args:
            extra_vars: |-
              {
                "system_name": "test1", 
                "timestamp": "test2", 
                "err_id": "test3", 
                "err_target": "test4", 
                "err_code": "test5", 
                "context": "test6", 
                "memo": "test7"
              }