---
- name: Error Recieve Rulebook
  hosts: localhost

  vars_files:
    - ./conf/err_rule_conf.yml

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Error Stop
      condition: event.payload.system_name is defined
      action:
        - run_job_template:
            name: Sample-apl Stop
            organization: Default

    - name: Auto Reboot
      condition: event.payload.system_name in system_list
      action:
        debug:
          msg: "auto reboot"

    - name: Recomfirm Reboot
      condition: event.payload.system_name not in system_list
      action:
        - run_job_template:
            name: Teams Action Notification
            organization: Default
            job_args: 
              extra_vars: 
                subject: '"[障害]{{ event.payload.err_id }}"'
                description: '"{{ event.payload.context }}"'
                system_name: '"{{ event.payload.system_name }}"'
                timestamp: '"{{ event.payload.timestamp }}"'
                err_id: '"{{ event.payload.err_id }}"'
                err_target: '"{{ event.payload.err_target }}"'
                err_code: '"{{ event.payload.err_code }}"'