- name: Trouble Recover Reboot Rulebook
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5002

  rules:
    - name: Reboot Sample-Apl
      condition: event.payload.request == "reboot"
      actions:
        - run_job_template:
            name: Sample-apl Start
            organization: Default

        - run_job_template:
            name: Redmine Issue Post
            organization: Default
            job_args: 
              extra_vars: 
                subject: '"[障害]{{ event.payload.err_id }}"'
                description: '"{{ event.payload.context }}\n{{ event.payload.memo }}"'
                system_name: '"{{ event.payload.system_name }}"'
                timestamp: '"{{ event.payload.timestamp }}"'
                err_id: '"{{ event.payload.err_id }}"'
                err_target: '"{{ event.payload.err_target }}"'
                err_code: '"{{ event.payload.err_code }}"'
                context: "-"