---
- name: Hello Events
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Data send
      condition: 
        all:
          - event.payload.datatype == "trouble"
          - event.payload.subject is defined
      action:
        run_job_template:
          name: test_playbook2
          organization: Default
          job_args:
            extra_vars:
              issue: "{{ event.payload.subject }}"